apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci_cd_traditional
on:
  push:
    branches:
      - "asd"
env:
  BUILD_ID: ${{ cloudbees.version }}
  NEXUS_API_RAW: ${{ vars.guru_rep_nexus_url }}/service/rest/v1/components?repository=raw
  APP_NAME: spring-petclinic-angular
jobs:
  build_TGZ:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://golang:1.20
        name: configure version
        run: |
          sed -i "s/\"version\": .*/\"version\": \"$BUILD_ID\",/" ./package.json
          cat ./package.json | grep "version"
        shell: sh
      - uses: docker://node:latest
        name: npm build
        kind: build
        run: |-
          npm install --force
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
          tar -cvzf dist.tgz ./dist
      - uses: docker://node:latest
        name: scan with sonar
        kind: scan
        run: 'echo "to be done: scan with sonar="'
      - uses: docker://alpine/helm:latest
        name: publish to nexus
        run: curl -v -u ${{ vars.guru_rep_nexus_user }}:${{ secrets.guru_rep_nexus_cred
          }}  -X POST '$NEXUS_API_RAW'
          -F raw.assetN=@./dist.tgz
          -F "raw.directory=/spring-petclinic-angular/latest"
          -F "raw.assetN.filename=spring-petclinic-angular.tgz"
  deploy:
    needs: build_TGZ
    steps:
      - uses: cloudbees-io/ssh-deploy-actions@v1
        with:
          host: ${{ vars.petclinic_ssh_host }}
          port: "22"
          username: ${{ vars.petclinic_cnp_username }}
          password: ${{ secrets.petclinic_cnp_pwd }}
          script: |-
            petclinicPID=`pm2 pid petclinic`
            if [ ! -z $petclinicPID ] ; then
              pm2 delete petclinic 2>&1 && return 0
            fi
            sudo docker pull springcommunity/spring-petclinic-rest:latest
            if [ \"$(sudo docker ps -q)\" ]; then
              sudo docker kill $(sudo docker ps -q)
              sudo docker run -d -p 8557:9966 springcommunity/spring-petclinic-rest:latest
            fi
            rm -rf spring-petclinic-angular.tgz
            rm -rf dist
            wget https://nexus.guru-rep.sa-demo.beescloud.com/repository/raw/spring-petclinic-angular/latest/spring-petclinic-angular.tgz
            tar -xvzf spring-petclinic-angular.tgz
            pm2 start $(which angular-http-server) --name petclinic -- --path ./dist