apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci_cd_modern
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  BUILD_ID: ${{ cloudbees.version }}
  NEXUS_HELM: ${{ vars.guru_rep_nexus_url }}/repository/helm-hosted/
jobs:
  build_docker:
    steps:
      - uses: docker://alpine/git:2.43.0
        name: check env vars
        run: |
          echo "BUILD_ID: $BUILD_ID"
          echo "NEXUS_HELM: $NEXUS_HELM"
      - uses: docker://alpine/git:2.43.0
        name: add safe dir
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: setup docker hub registry
        with:
          registry: index.docker.io
          username: ${{ vars.GURUREP_DOCKER_USERNAME }}
          password: ${{ secrets.GURUREP_DOCKER_PASSWORD }}
      - uses: cloudbees-io/kaniko@v1
        name: build docker
        kind: build
        with:
          dockerfile: Dockerfile
          destination: gururepservice/spring-petclinic-angular:${{ cloudbees.version
            }},gururepservice/spring-petclinic-angular:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=Jakub Zarzycki,version=1.2.3.4
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: sonarqube scan
        kind: scan
        with:
          language: JAVASCRIPT
      - uses: cloudbees-io/publish-evidence-item@v1
        name: publish evidence
        with:
          content: |-
            ## Docker image
            gururepservice/spring-petclinic-angular:${{ cloudbees.version}}
  manage_chart:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://golang:1.20
        name: configure
        run: >
          sed -i "s/^version:.*$/version: $BUILD_ID/"
          chart/spring-petclinic-angular/Chart.yaml

          sed -i "s/^appVersion:.*$/appVersion: $BUILD_ID/" chart/spring-petclinic-angular/Chart.yaml

          sed -i "s/^  tag:.*$/  tag: $BUILD_ID/" chart/spring-petclinic-angular/values.yaml

          cat chart/spring-petclinic-angular/Chart.yaml
        shell: sh
      - uses: docker://alpine/helm:latest
        name: package
        run: |
          cd chart
          helm version
          helm package spring-petclinic-angular
          ls -lart
        shell: sh
      - uses: guru-actions/helm-push@1.6
        name: publish
        with:
          chart_package: chart/spring-petclinic-angular-$BUILD_ID.tgz
          remote_repo: $NEXUS_HELM
          remote_user_name: ${{ vars.guru_rep_nexus_user }}
          remote_password: ${{ secrets.guru_rep_nexus_cred }}
    needs: build_docker
  deploy_k8s:
    environment: petclinic-dev
    steps:
      - uses: guru-actions/kubeconfig@1.11
        name: setup kubeconf
        with:
          secname: ${{ secrets.guru_rep_petclinic_kubeconf }}
      - uses: docker://bitnami/kubectl:latest
        name: check kubeconf
        run: kubectl get pods
      - uses: guru-actions/helm-deploy@1.23
        name: deploy chart
        kind: deploy
        with:
          chart: spring-petclinic-angular/spring-petclinic-angular
          repo: $NEXUS_HELM
          namespace: petclinic
          release: petclinic-fm
          version: $BUILD_ID
          repousername: ${{ vars.guru_rep_nexus_user }}
          repopassword: ${{ secrets.guru_rep_nexus_cred }}
    needs:
      - manage_chart
      - build_backend_jenkins
  build_backend_jenkins:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: trigger_cbci
        kind: build
        with:
          url: https://core.cloudbees.guru/shared-demos
          username: ${{vars.GURUCI_USERNAME}}
          token: ${{secrets.GURUCI_TOKEN}}
          job-name: spring-petclinic/job/spring-petclinic-angular-backend/
          parameters: '{"version":"${{ cloudbees.version }}"}'
      - uses: cloudbees-io/publish-evidence-item@v1
        name: publish evidence
        with:
          content: |-
            ## Backend Build
            "version":"${{ cloudbees.version }}"
