apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: withLaunchable
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  BUILD_ID: ${{ cloudbees.version }}
  NEXUS_HELM: ${{ vars.guru_rep_nexus_url }}/repository/helm-hosted/
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
jobs:
  build_docker:
    steps:
      - uses: docker://alpine/git:2.43.0
        name: check env vars
        run: |
          echo "BUILD_ID: $BUILD_ID"
          echo "NEXUS_HELM: $NEXUS_HELM"
      - uses: docker://alpine/git:2.43.0
        name: add safe dir
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://gururepservice/launchable:latest
        name: launchable verify
        run: |
          launchable verify || true
